[package]

name = "krello"
version = "0.0.1"
authors = ["Djoe Pramono"]

http.check-revoke = false

edition = "2018"
[dependencies]
clap = "3.0.0-beta.1"
reqwest = { version = "0.10.0-alpha.2", features = ["blocking"] }
error-chain = "0.12.2"
